// Pre-defined question paths based on keywords
const TRIAGE_PATHS = {
  headache: [
    "Is the pain throbbing or pulsing?",
    "Are you sensitive to light or sound?",
    "Have you experienced any vision changes?",
    "Did the headache start suddenly and severely?"
  ],
  cough: [
    "Are you coughing up any mucus or phlegm?",
    "Do you have a fever?",
    "Are you experiencing shortness of breath?",
    "Has the cough lasted for more than 3 weeks?"
  ],
  stomach: [
    "Is the pain sharp and severe?",
    "Is the pain located in the lower right side?",
    "Have you been experiencing nausea or vomiting?",
    "Have you noticed a change in your bowel movements?"
  ],
  fever: [
    "Is your temperature above 101°F (38.3°C)?",
    "Are you experiencing chills or body aches?",
    "Do you have a stiff neck?",
    "Have you been exposed to anyone who is currently sick?"
  ],
  default: [
    "Did this symptom start suddenly within the last 24 hours?",
    "Are you experiencing any severe pain?",
    "Does the symptom get worse with movement?",
    "Have you taken any medication for this yet?"
  ]
};

// Helper to determine the path based on the initial complaint
function determinePath(initialComplaint) {
  const text = initialComplaint.toLowerCase();
  if (text.includes("head") || text.includes("migraine")) return TRIAGE_PATHS.headache;
  if (text.includes("cough") || text.includes("chest") || text.includes("throat") || text.includes("breath")) return TRIAGE_PATHS.cough;
  if (text.includes("stomach") || text.includes("belly") || text.includes("nausea") || text.includes("pain") || text.includes("vomit")) return TRIAGE_PATHS.stomach;
  if (text.includes("fever") || text.includes("hot") || text.includes("chill")) return TRIAGE_PATHS.fever;
  return TRIAGE_PATHS.default;
}

export async function generateNextQuestion(history, questionCount) {
  // Simulate network delay for realistic "Analyzing" feel
  await new Promise(res => setTimeout(res, 800));

  // The first history item is always the initial complaint
  const initialComplaint = history[0]?.answer || "";
  const questions = determinePath(initialComplaint);

  // If we've asked all 4 questions, or we are past questionCount 4, conclude.
  // Note: questionCount starts at 1, so indices are questionCount - 1
  if (questionCount > questions.length) {
    return {
      question: "Thank you for the details. I will send this to the doctor now.",
      options: ["Finish Triage"]
    };
  }

  // Return the next question in the sequence
  return {
    question: questions[questionCount - 1],
    options: ["Yes", "No", "Not sure"]
  };
}

export async function generateSummary(history) {
  // Fast generation of summary
  await new Promise(res => setTimeout(res, 500));

  let summary = `### Patient Triage Report\n\n`;
  summary += `**Primary Complaint:** ${history[0]?.answer || 'Unknown'}\n\n`;
  summary += `**Follow-up Analysis:**\n`;
  
  for (let i = 1; i < history.length; i++) {
    const item = history[i];
    // Bold 'Yes' answers for quick doctor scanning
    const isRedFlag = item.answer === 'Yes';
    summary += `- ${item.question} **${item.answer}**\n`;
  }
  
  summary += `\n*Note: This summary was generated by the internal scripted triage engine.*`;
  
  return summary;
}
