import React from 'react';

export function Terms() {
  return (
    <div className="bg-white text-black min-h-screen">
      <div className="max-w-4xl mx-auto py-12 px-6 sm:px-8 lg:px-12 font-sans">
        
        {/* Header */}
        <div className="border-b border-gray-300 pb-8 mb-8">
          <h1 className="text-4xl font-bold tracking-tight mb-4">Terms and Conditions</h1>
          <p className="text-gray-600 text-sm">Effective Date: {new Date().toLocaleDateString()}</p>
        </div>

        {/* Content */}
        <div className="prose prose-sm sm:prose-base max-w-none text-gray-800 space-y-8">
          
          <section>
            <h2 className="text-2xl font-semibold mb-4 text-black">1. Introduction and Acceptance of Terms</h2>
            <p>
              Welcome to MediPreCheck. These Terms and Conditions ("Terms") govern your access to and use of the MediPreCheck application, website, and related services (collectively, the "Service"). 
              By accessing or using the Service, you agree to be bound by these Terms and our Privacy Policy. If you do not agree with any part of these Terms, you must not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-black">2. Nature of the Service and Medical Disclaimer</h2>
            <p>
              <strong>2.1 Software Assistance Only.</strong> MediPreCheck is designed to act solely as a software assistant. The Service analyzes user inputs to provide suggestions, recommendations, and preliminary information to assist clinical workflows. 
            </p>
            <p className="mt-4">
              <strong>2.2 Not a Substitute for Medical Judgment.</strong> The suggestions or recommendations generated by the Service are for informational purposes only. The Service does not provide medical diagnoses, treatment plans, or definitive medical advice. 
              <strong> The final clinical decision, diagnosis, and treatment plan must always be determined by a qualified, licensed healthcare professional (e.g., a doctor or physician).</strong>
            </p>
            <p className="mt-4">
              <strong>2.3 No Emergency Use.</strong> The Service is not intended for use in medical emergencies. If you believe you are experiencing a medical emergency, you must immediately contact emergency services or visit the nearest hospital.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-black">3. User Responsibilities</h2>
            <p>
              <strong>3.1 Accuracy of Information.</strong> Users (including patients and clinic staff) are responsible for ensuring that all information, medical history, and symptoms submitted through the Service are accurate, complete, and up-to-date. MediPreCheck is not liable for recommendations generated based on inaccurate, incomplete, or false information provided by the user.
            </p>
            <p className="mt-4">
              <strong>3.2 Compliance with Laws.</strong> You agree to use the Service in compliance with all applicable local, state, national, and international laws, rules, and regulations, including those pertaining to data privacy and healthcare (such as HIPAA, where applicable).
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-black">4. Data Privacy and Confidentiality</h2>
            <p>
              We take the privacy and security of your health information seriously. All data transmitted through the Service is encrypted and handled in accordance with applicable healthcare privacy regulations. However, no digital platform can guarantee absolute security. By using the Service, you acknowledge and accept the inherent risks of transmitting information over the internet.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-black">5. Intellectual Property</h2>
            <p>
              All intellectual property rights in the Service, including software, algorithms, designs, text, and graphics, are owned by or licensed to MediPreCheck. You may not copy, modify, distribute, sell, or lease any part of our Service or included software without explicit written permission.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-black">6. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by applicable law, MediPreCheck, its affiliates, directors, employees, and agents shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising out of or related to your use of the Service. 
              This includes, but is not limited to, any damages resulting from reliance on the software’s suggestions, delays in treatment, or data breaches, regardless of whether MediPreCheck has been advised of the possibility of such damages.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-black">7. Modifications to the Terms</h2>
            <p>
              We reserve the right to modify or replace these Terms at any time at our sole discretion. It is your responsibility to review these Terms periodically for changes. Your continued use of the Service following the posting of any changes constitutes acceptance of those changes.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold mb-4 text-black">8. Governing Law</h2>
            <p>
              These Terms shall be governed and construed in accordance with the laws of the jurisdiction in which MediPreCheck operates, without regard to its conflict of law provisions.
            </p>
          </section>
          
          <section className="pt-8 border-t border-gray-300 mt-12">
            <p className="text-sm text-gray-500">
              If you have any questions about these Terms, please contact the clinic administrator or support team.
            </p>
          </section>
        </div>

      </div>
    </div>
  );
}
