import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Card, CardHeader, CardTitle, CardContent } from '../../components/ui/Card';
import { Button } from '../../components/ui/Button';
import { Users, Clock, ChevronRight } from 'lucide-react';

export function DoctorQueue() {
  const navigate = useNavigate();
  const [queue, setQueue] = useState([]);

  useEffect(() => {
    // Read dynamic queue from localStorage generated by the Kiosk
    const loadedQueue = JSON.parse(localStorage.getItem('doctor_queue') || '[]');
    setQueue(loadedQueue.reverse()); // Show newest first
  }, []);

  return (
    <div className="space-y-8 animate-in fade-in duration-500 max-w-4xl mx-auto mt-8">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-4xl font-bold tracking-tight">Live Queue</h1>
          <p className="text-muted-foreground mt-2 text-lg">Patients currently waiting in the clinic.</p>
        </div>
        <Card glass className="px-6 py-3 flex items-center space-x-4">
          <div className="p-3 bg-green-500/10 rounded-full text-green-500">
            <Users className="w-5 h-5" />
          </div>
          <div>
            <p className="text-sm text-muted-foreground font-medium">Ready for Review</p>
            <p className="text-2xl font-bold">{queue.length}</p>
          </div>
        </Card>
      </div>

      <div className="grid gap-4">
        {queue.length === 0 ? (
          <div className="text-center p-12 bg-muted/50 rounded-xl border border-dashed">
            <p className="text-muted-foreground text-lg">No patients in the queue right now.</p>
          </div>
        ) : (
          queue.map((item, idx) => (
            <Card glass key={`${item.token}-${idx}`} className="relative overflow-hidden group">
              <div className="absolute top-0 left-0 w-2 h-full bg-green-500"></div>
              <div className="flex items-center justify-between p-6">
                <div className="flex items-center gap-6">
                  <h3 className="text-3xl font-bold tracking-wider">{item.token}</h3>
                  <div className="space-y-1">
                    <span className="inline-block px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400">
                      Triage Complete
                    </span>
                    <div className="flex items-center text-sm text-muted-foreground">
                      <Clock className="w-3 h-3 mr-1" /> Arrived: {item.timeWaiting}
                    </div>
                  </div>
                </div>
                
                <Button 
                  onClick={() => navigate(`/doctor/review/${item.token}`)}
                  className="h-12 px-6"
                >
                  Review Patient
                  <ChevronRight className="w-5 h-5 ml-2" />
                </Button>
              </div>
            </Card>
          ))
        )}
      </div>
    </div>
  );
}
